name: New Post
description: Buat artikel baru
title: "post: judul artikel"
labels: ["content:post"]
body:
  - type: input
    id: slug
    attributes: 
      label: Slug (tanpa spasi)
      placeholder: 2025-09-judul-artikel
    validations: { required: true }

  - type: input
    id: title
    attributes: 
      label: Judul
      placeholder: Judul Artikel
    validations: { required: true }

  - type: input
    id: date
    attributes: 
      label: Tanggal (YYYY-MM-DD)
      placeholder: 2025-09-01
    validations: { required: true }

  - type: input
    id: tags
    attributes: 
      label: Tags (koma)
      placeholder: kuliah,ai

  - type: textarea
    id: summary
    attributes: 
      label: Ringkasan
      placeholder: Ringkasan singkat…

  - type: textarea
    id: content
    attributes: 
      label: Isi artikel (Markdown)
      placeholder: Tulis konten di sini…
